#!/bin/bash
chmod u+x [0-99]*; git add . ; git commit -am "commit message" ; cat eslam-atwa; cat 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; git push; cat eslam-atea ; cat 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 ;
